name: step_challenge_app
description: A health step tracking and challenge app with Google Sheets integration.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Health data
  health: ^13.1.1
  permission_handler: ^11.0.1
  
  # Google Sheets API
  googleapis: ^13.0.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  
  # Push notifications
  flutter_local_notifications: ^16.3.0
  
  # UI and animations
  flutter_animate: ^4.3.0
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.6
  
  # QR Code and sharing
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  share_plus: ^7.2.1
  
  # State management
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true