name: step_challenge_app
description: A health step tracking and challenge app with Google Sheets integration.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Health data
  health: ^10.2.0
  permission_handler: ^11.0.1
  
  # Google Sheets API
  googleapis: ^13.0.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  
  # Push notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.3.0
  
  # UI and animations
  flutter_animate: ^4.3.0
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.6
  
  # State management
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700